### ISSUE TITLE
Should data set be 'storms' instead of 'storm' ?

### ISSUE THREAD

**Issue by mleporibui** [laurelabowd/issues_lab#1]
Hi, I think this data set should be called 'storms' instead of 'storm'

https://github.com/laurelabowd/issues_lab/blob/fef848a93bc3e0aef284e2cd84fcda940b78ecd3/got_issues.Rmd#L18

**Comment by laurelabowd** [comment]
Thanks, Michelle! I updated the rmd file to use data 'storms'
